# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your Gradle project build, please visit
# https://developer.android.com/studio/build

# Use the latest version of the Android Gradle plugin
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Encoder for Android URI encoding/decoding. Possible values: 'java7', 'java8'.
# The java8 option is faster and should be used if the app runs on Java 8 or later (API 24+)
# As this project targets API 24+, it is safe to use java8
android.encoder=java8

# Specifies the JDK version for the current project
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
